version: 2.1
jobs:
  build:
    working_directory: ~/UIAPIAuto_QATest
    docker:
      - image: circleci/node:10.16.3 
      - image: mongo:4.2.0 
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: reportfile
          command: npm run makereportdirectory
      - run:
          name: reportfileMerge
          command: npm run mergeMochaReport            
     
      - store_artifacts:        
          path: mochareports\report.html
          prefix: tests
      - store_test_results:
          path: mochareports\report.html